### NUMPY

In [1]:
import numpy as np

###### 1) 배열(ndarray) 다루기

In [2]:
a = np.array([1, 2, 3, 4, 5, 6], dtype='i')
a

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [10]:
a.ndim # ndim : 차원 -> []의 두께

1

In [5]:
a.shape # m행 n열 -> a: 6행 1열 (1은 생략)

(6,)

In [6]:
a.dtype

dtype('int32')

In [7]:
a.astype('f')

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [8]:
a.astype('O')

array([1, 2, 3, 4, 5, 6], dtype=object)

기호 | <center>b</center> | **i** | i8 | u | f | O  
- | - | - | - | - | - | -
 타입 | **boolean** | int32 | int64 | uint32 | float32 | object

In [3]:
data = [[1, 2], [3, 4]] # 리스트
data_arr = np.array(data)
data_arr

array([[1, 2],
       [3, 4]])

In [4]:
data_arr.ndim

2

In [9]:
data_arr.shape

(2, 2)

In [10]:
data_arr.dtype

dtype('int32')

###### 2) 다양한 배열 생성 메서드

- zeros, ones('scalar/tuple/list', dtype=)
- zeros_like(다른 배열), ones_like
- empty
- arange(시작, 끝(포함x), 단계)
- linespace(시작, 끝(포함o), 갯수)
- logspace(시작, 끝(포함o), 갯수)
- rand
- randn

In [11]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [12]:
zeros = np.zeros((4, 5), dtype='O')
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=object)

In [13]:
zeros_2 = np.zeros_like(ones)
zeros_2

array([0., 0., 0., 0., 0.])

In [14]:
empty = np.empty((4, 5))
empty

array([[9.92684954e-312, 6.07700744e-322, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307],
       [1.16095484e-028, 9.26724956e+242, 5.49419094e-143,
        6.96410748e+252, 8.03408341e-095],
       [5.72974605e+194, 1.16589870e-028, 1.47763669e+248,
        4.78214477e+180, 1.16441574e-028],
       [5.38669143e+228, 7.79350126e-143, 3.97084747e+246,
        2.03789108e+180, 2.15799225e+243]])

In [15]:
linspace = np.linspace(0, 100, 5)
linspace

array([  0.,  25.,  50.,  75., 100.])

In [16]:
logspace = np.logspace(0, 1, 5)
logspace

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [17]:
np.inf

inf

In [18]:
np.nan #not a number

nan

* Numpy의 강점 1. 벡터화 연산

In [21]:
data = np.array([1, 2, 3, 4, 5, 6])
2 * data

array([ 2,  4,  6,  8, 10, 12])

- Numpy의 강점 2. 변환

In [33]:
data = data.reshape(2, 3) #6행1열 -> 2행3열
data

array([[1, 2, 3],
       [4, 5, 6]])

- Numpy의 강점 3. 배열 인덱싱 ( = query 기능 )

In [37]:
data[[1, 0]] #data[1]와 data[0]

array([[4, 5, 6],
       [1, 2, 3]])

In [40]:
data[[1, 0], :] # : 전부 지칭 -> data[1, :]와 data[0, :]

array([[4, 5, 6],
       [1, 2, 3]])

In [41]:
data[:, [2, 0, 1]]

array([[3, 1, 2],
       [6, 4, 5]])

In [25]:
data%2 == 0

array([[False,  True, False],
       [ True, False,  True]])

In [42]:
data[data%2 == 0] #data 중에 짝수인 애들만 지정

array([2, 4, 6])

In [27]:
data[0, :] # slicing

array([1, 2, 3])

In [29]:
idx = np.array([0, 2])

In [30]:
data[0, idx]

array([1, 3])

In [31]:
idx2 = np.array([0, 0, 1, 1, 1, 2])

In [32]:
data[1, idx2]

array([4, 4, 5, 5, 5, 6])

###### 2) 난수 발생

- randint(시작, 끝, size='scalar' or 'tuple/list')  
- 

In [153]:
age = np.random.randint(1, 100, size=(3, 5))
age[:10]

array([[25, 99, 65, 41, 93],
       [27, 78, 31, 70, 99],
       [43, 35, 80, 86, 67]])

In [43]:
data_rand = np.random.rand(10)
data_rand

array([0.2628384 , 0.54951406, 0.3574185 , 0.70250848, 0.03790241,
       0.12312157, 0.99724017, 0.62476231, 0.07008814, 0.93779548])

In [44]:
data_randn = np.random.randn(10)
data_randn

array([ 0.33196492, -0.8993991 , -0.7353399 ,  0.80781675, -1.12018845,
        1.60760246,  1.82523901, -0.09378512, -0.74245355, -0.85734973])