# Scikit_learn

전반적인 머신러닝 패키지  
linear regression, logistic regression, SVM, kernel-SVM, decision Tree, Random Forest, Adaboost, PCA, Multiperceptron 등등

샘플 데이터셋 제공

In [3]:
from sklearn.datasets import load_boston

In [4]:
boston = load_boston()
boston 

{'DESCR': "Boston House Prices dataset\n===========================\n\nNotes\n------\nData Set Characteristics:  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive\n    \n    :Median Value (attribute 14) is usually the target\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per

자세히 들여다보면, boston이라는 변수는 dictionary형태라는 것을 알 수 있다. -> '키'값을 지정하면, 그에 대한 'value'를 얻을 수 있다.

In [8]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

일일이 살펴보면 알 수 있겠지만,  
data에는 부동산 가치를 결정짓는 요인, 즉 X_feature 데이터가 들어 있다
  
target에는 부동산 가치, 즉 y 데이터가 들어있다.
  
feature_names에는 부동산 가치를 결정짓는 요인들이 들어 있다.

In [9]:
boston['data']

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

array로 되어있으니, shape을 찍어볼 수 있다.

In [10]:
boston['data'].shape

(506, 13)

506 x 13이 각각 의미하는 게 뭘까?

In [11]:
boston['feature_names'] #이건 부동산가치결정요인들이다. 이게 13개다.

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [13]:
boston['target'].shape #506 x 1

(506,)

boston의 데이터는 총 506개의 부동산 데이터가 있고,  
x_feature는 13개, y는 price 1개 값이 있는 것이다.

#### 모델 학습

자, 머신러닝 모델 학습을 시켜보자.  
이는 regression이기 때문에, linear regression모델을 사용하자.

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [21]:
X_tr, X_ts, y_tr, y_ts = train_test_split(boston['data'],
                                         boston['target'],
                                         shuffle=True)

In [22]:
model = LinearRegression()
model.fit(X_tr, y_tr)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

학습이 완료되었다.  
그렇다. sklearn에서는 model 객체를 만들고,  
model을 이용해, 학습데이터를 넣어주고, fit을 하면 학습이 완료된다.

#### 모델 학습 결과 확인

In [23]:
model.coef_

array([-7.90313491e-02,  5.83707964e-02,  4.15172745e-02,  3.57571349e+00,
       -1.68526669e+01,  4.16803575e+00, -4.43268344e-03, -1.68267563e+00,
        3.35813027e-01, -1.38813574e-02, -8.67968677e-01,  1.38750798e-02,
       -5.17720001e-01])

In [24]:
model.intercept_

31.51544990947919

coef_가 바로 weight다.  
intercept_가 bias다.

#### model 검증

In [25]:
#accuracy
model.score(X_ts, y_ts)

0.7238824118935929

In [26]:
#예측 
model.predict(X_ts)

array([26.03010321, 36.14686515, 38.93800731, 21.59131771, 21.29916782,
       36.42074937, 19.1002286 , 25.81088965, 28.29724843, 21.15094693,
       30.5240493 , 20.6294602 , 32.70505653, 18.5262007 , 38.04224952,
       21.93353208, 28.28095335, 28.20229452, 13.95417596, 29.08029109,
       21.60119155, 20.63268645, 27.48602023, 20.02449806, 18.0574828 ,
       25.51800793, 18.66124266, 18.6720577 , 37.68721347, 22.36310816,
       18.12422366, 19.97385381, 25.06844666, 24.103505  , 30.81084798,
        6.7993631 , 24.40737098, 21.56922944, 43.43796664, 17.575517  ,
       30.97091234, 12.45240727, 22.95399085,  8.29115752, -4.06446003,
       38.54634138,  9.88402278, 26.75037491, 21.7205805 , 27.67229797,
       20.6038866 , 15.31624853, 25.15000204, 29.86609912, 13.37513015,
       22.79484843, 17.50291626, 28.63416664, 36.08451062, 11.87182918,
       18.29842124, 27.07144303, 20.66785587,  8.28706266, 24.69052097,
       37.47612017, 20.79670265, 23.24314882, 21.52460891, 13.41

homework) logistic regression을 이용해서, load_wine데이터를 머신러닝 모델링해보자.

In [2]:
from sklearn.datasets import load_wine

from sklearn.linear_model import LogisticRegression

In [4]:
wine_data = load_wine()
wine_data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [7]:
import pandas as pd
X_wine_df = pd.DataFrame(wine_data['data'], columns=wine_data['feature_names'])
X_wine_df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [11]:
y_wine_df = pd.DataFrame(wine_data['target'], columns=['wine_type'])
y_wine_df.head()

wine_type
0          0
1          0
2          0
3          0
4          0

In [17]:
from sklearn.model_selection import train_test_split

X_tr, X_ts, y_tr, y_ts = train_test_split(X_wine_df, y_wine_df,
                                         test_size=0.2,
                                         shuffle=True)

In [18]:
#model training
model = LogisticRegression()
model.fit(X_tr, y_tr)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [21]:
X_tr.shape #n_feature = 13개 -> weight -> 13, bias -> 1

(142, 13)

In [22]:
model.coef_.shape # 3 x 13개 

(3, 13)

In [23]:
model.intercept_.shape # 3 x 1개

(3,)

In [24]:
model.score(X_ts, y_ts)

0.9722222222222222

In [27]:
model.score(X_tr, y_tr)

0.9788732394366197

In [35]:
pred_ts = model.predict(X_ts) #testset의 예측값
pred_ts

array([0, 1, 2, 0, 2, 2, 1, 1, 2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 1,
       0, 1, 0, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1])

In [34]:
import numpy as np
y_ts = np.array(y_ts).flatten()
y_ts

array([0, 1, 2, 0, 2, 2, 1, 1, 2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 2,
       0, 1, 0, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1])

In [39]:
acc_ts = np.mean(np.equal(y_ts, pred_ts).astype(int))
acc_ts

0.9722222222222222